### ISSUE TITLE
Clarify documentation title for load_jhu_data

### ISSUE THREAD

**Issue by brookslogan** [reichlab/covidData#13]
The title for `load_jhu_data` in the documentation is "Construct table of truths for weekly incident and cumulative deaths at horizons one though 6", but outputs a data frame with columns `location`, `date`, `inc`, `cum` (no `ahead`), with more than 6 unique `date`s.  Would "Construct tbl_df of observed weekly incident and cumulative deaths" be more accurate?

**Comment by elray1** [comment]
thanks for this suggestion -- i just updated it
